FROM pytorch/pytorch:1.13.1-cuda11.6-cudnn8-runtime
ENV JUPYTER_CONFIG_DIR=/data/jupyter/
COPY requirements.txt ./
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y gcc
RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements.txt